import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { HeaderWraper } from '../components/Header'
import { HomeAbout } from '../components/Home.about'
import { HomeContact } from '../components/Home.contact'
import { HomeFooter } from '../components/Home.footer'
import { HomePortfolio } from '../components/Home.portfolio'
import { HomeSkills } from '../components/Home.skills'
import { HomeWelcome } from '../components/Home.welcome'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ opacity: "1" }} className="page-wrapper">
        <HeaderWraper />
        <HomeWelcome />
        <HomeAbout />
        <HomeSkills />
        <HomePortfolio />
        <HomeContact />
        <HomeFooter />
      </div>
      <div className="loading-bar-wrapper" style={{ display: "none", opacity: 0 }}>
        <div className="loading-bar" style={{ width: "100vw" }}></div>
      </div>
    </>
  )
}

export default Home
